# Generated by Django 6.0.7 on 2026-08-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(blank=True, max_length=100, verbose_name='Отец')),
                ('mother', models.CharField(blank=True, max_length=100, verbose_name='Мать')),
                ('grandfather_father', models.CharField(blank=True, max_length=100, verbose_name='Дед по отцу')),
                ('grandmother_father', models.CharField(blank=True, max_length=100, verbose_name='Бабка по отцу')),
                ('grandfather_mother', models.CharField(blank=True, max_length=100, verbose_name='Дед по матери')),
                ('grandmother_mother', models.CharField(blank=True, max_length=100, verbose_name='Бабка по матери')),
                ('awards', models.TextField(blank=True, verbose_name='Награды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='dogs.dog', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Родословная',
                'verbose_name_plural': 'Родословные',
            },
        ),
    ]
