# Generated by Django 6.0.7 on 2026-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_pedigree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'permissions': [('can_change_active', 'Может менять активность'), ('can_change_owner', 'Может менять владельца')], 'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
